package prototipop1;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SEBAS
 */
public class intVenta extends javax.swing.JInternalFrame {

    DefaultTableModel model = new DefaultTableModel();
    String subtotal;
    
   
    /**
     * Creates new form intCompra
     */
    public intVenta() {
        initComponents();
        txt_precio.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txt_idProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnAgregarProducto = new javax.swing.JButton();
        btnFinCompra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btn_confirmar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_idventa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_nitcliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_fecha = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        jLabel5.setText("Producto");

        txt_idProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_idProductoKeyReleased(evt);
            }
        });

        jLabel7.setText("Cantidad");

        txt_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cantidadKeyReleased(evt);
            }
        });

        jLabel8.setText("TOTAL");

        jLabel9.setText("Precio");

        btnAgregarProducto.setText("Agregar al Carrito");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        btnFinCompra.setText("Finalizar Compra");
        btnFinCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinCompraActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IdVenta", "IdProducto", "Cantidad", "SubTotal"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        btn_confirmar.setText("Confirmar");
        btn_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmarActionPerformed(evt);
            }
        });

        jLabel6.setText("ID");

        txt_idventa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_idventaKeyReleased(evt);
            }
        });

        jLabel10.setText("Nit Cliente");

        txt_nitcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nitclienteKeyReleased(evt);
            }
        });

        jLabel11.setText("Fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                        .addComponent(txt_idventa)
                                        .addComponent(txt_nitcliente))
                                    .addComponent(btn_confirmar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_idProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_cantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_precio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnFinCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnAgregarProducto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(9, 9, 9)
                        .addComponent(btnFinCompra))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_idventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_nitcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_confirmar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_idProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarProducto)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        // TODO add your handling code here:
        
        
        try {
            Connection cn = DriverManager.getConnection(mdi_Principal.BD, mdi_Principal.Usuario, mdi_Principal.Contraseña);
            
            //Guardando en el detalle de la venta
            PreparedStatement pst1 = cn.prepareStatement("insert into venta_d values(?,?,?,?)");

            //
            pst1.setString(1, txt_idventa.getText().trim());
            pst1.setString(2, txt_cantidad.getText().trim());
            pst1.setString(3, txt_idProducto.getText().trim());
            pst1.setString(4, txt_precio.getText().trim());

            pst1.executeUpdate();           
       
            //Llenando la tabla
            
             this.tabla.setModel(model); 
            String titulo[] = {"Id_Venta", "Id_Producto", "Cantidad", "Precio"};
            model.setColumnIdentifiers(titulo);
            
            String registros[] = new String[100];
            
            registros[0] = txt_idventa.getText();
            registros[1] = txt_idProducto.getText();
            registros[2] = txt_cantidad.getText();
            registros[3] = txt_precio.getText();
            model.addRow(registros);

            JOptionPane.showMessageDialog(this, "¡REGISTRO EXITOSO!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            txt_cantidad.setText("");
            txt_precio.setText("");
            txt_idProducto.setText("");
            sumaColumnaPrecio();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error en registro", "Warning", JOptionPane.WARNING_MESSAGE);
            System.out.println(e);
        }
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnFinCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinCompraActionPerformed
        // TODO add your handling code here:
        
            txt_idProducto.setText("");
            txt_cantidad.setText("");
            txt_idventa.setText("");
            txt_fecha.setCalendar(null);
            txt_total.setText("");
            txt_cantidad.setText("");
            txt_precio.setText("");
            txt_nitcliente.setText("");
            
            txt_idventa.setEnabled(true);
            txt_fecha.setEnabled(true);
            txt_nitcliente.setEnabled(true);
            btn_confirmar.setEnabled(true);
            
            model.setRowCount(0);
    }//GEN-LAST:event_btnFinCompraActionPerformed

    private void btn_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmarActionPerformed
        // TODO add your handling code here:
        java.util.Date date = txt_fecha.getDate();
        long fechaD = date.getTime();
        java.sql.Date fecha = new java.sql.Date(fechaD);
        
        try{
          //Guardando en el encabezado de la compra
            Connection cn = DriverManager.getConnection(mdi_Principal.BD, mdi_Principal.Usuario, mdi_Principal.Contraseña);
            PreparedStatement pst = cn.prepareStatement("insert into venta_e values(?,?,?)");
            
            
            
            pst.setString(1, txt_idventa.getText().trim());
            pst.setString(2, txt_nitcliente.getText());
            pst.setString(3,fecha.toString());

            pst.executeUpdate();
            
             JOptionPane.showMessageDialog(this, "¡VENTA AUTORIZADA!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);

             txt_idventa.setEnabled(false);
             txt_nitcliente.setEnabled(false);
             txt_fecha.setEnabled(false);
             btn_confirmar.setEnabled(false);
             
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error en registro", "Warning", JOptionPane.WARNING_MESSAGE);
            System.out.println(e);
        }
        
    }//GEN-LAST:event_btn_confirmarActionPerformed

    private void txt_idProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idProductoKeyReleased
        // TODO add your handling code here:
          String id = txt_idProducto.getText();
        try{
        Connection cn = DriverManager.getConnection(mdi_Principal.BD, mdi_Principal.Usuario, mdi_Principal.Contraseña);
        PreparedStatement  pst = cn.prepareStatement("select precio from producto where id_producto = ?");
        pst.setString(1, id);
        
        ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                subtotal= rs.getString("precio");
            }
            else{
                 JOptionPane.showMessageDialog(this, "No se encontro el prodcuto.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        
        }
        catch (Exception e){
            System.out.println(e);
              JOptionPane.showMessageDialog(this, "Error en busqueda", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_idProductoKeyReleased

    private void txt_cantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadKeyReleased
        // TODO add your handling code here:
                  String id = txt_idProducto.getText();
        try{
            int intPrecio, intCant, intSubtotal;
            intCant = Integer.parseInt(txt_cantidad.getText());
            intSubtotal = Integer.parseInt(subtotal);
            intPrecio = intSubtotal * intCant;
            
            txt_precio.setText(intPrecio + "");
        }
        catch (Exception e){
            System.out.println(e);
              JOptionPane.showMessageDialog(this, "Error en operacion", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_cantidadKeyReleased

    private void txt_idventaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idventaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idventaKeyReleased

    private void txt_nitclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nitclienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nitclienteKeyReleased

   public void sumaColumnaPrecio(){
        double total = 0;
        double fila =0;
        for (int i = 0; i < tabla.getRowCount(); i++) {
            fila = Double.parseDouble(tabla.getValueAt(i,3).toString());
            total += fila;
        }
    
        txt_total.setText(total + "");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnFinCompra;
    private javax.swing.JButton btn_confirmar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txt_cantidad;
    private com.toedter.calendar.JDateChooser txt_fecha;
    private javax.swing.JTextField txt_idProducto;
    private javax.swing.JTextField txt_idventa;
    private javax.swing.JTextField txt_nitcliente;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
